name: datvir

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: datviruser
      POSTGRES_PASSWORD: datvirpass
      POSTGRES_DB: datvirdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations/postgres:/docker-entrypoint-initdb.d
    networks:
      - datvirnet

  timescaledb:
    image: timescale/timescaledb-ha:pg16
    environment:
      POSTGRES_USER: datviruser
      POSTGRES_PASSWORD: datvirpass
      POSTGRES_DB: datvirdb
    ports:
      - "5433:5432"
    volumes:
      - tsdata:/var/lib/postgresql/data
      - ./migrations/timescale:/docker-entrypoint-initdb.d
    networks:
      - datvirnet

  clickhouse:
    image: clickhouse/clickhouse-server:25.5-alpine
    ports:
      - "8123:8123"
      - "9123:9000"
    volumes:
      - chdata:/var/lib/clickhouse
      - ./migrations/clickhouse:/docker-entrypoint-initdb.d
    networks:
      - datvirnet

  mongodb:
    image: mongo:6.0.14
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      - ./migrations/mongo:/docker-entrypoint-initdb.d
    networks:
      - datvirnet

volumes:
  pgdata:
  tsdata:
  chdata:
  mongodata:

networks:
  datvirnet:
