name: datvirdb

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: datviruser
      POSTGRES_PASSWORD: datvirpass
      POSTGRES_DB: datvirdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    networks:
      - dbnet

  timescale:
    image: timescale/timescaledb-ha:pg16
    environment:
      POSTGRES_USER: datviruser
      POSTGRES_PASSWORD: datvirpass
      POSTGRES_DB: datvirdb
    ports:
      - "5433:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./timescale:/docker-entrypoint-initdb.d
    networks:
      - dbnet

#  clickhouse:
#    image: clickhouse/clickhouse-server:25.5-alpine
#    environment:
#      CLICKHOUSE_USER: datviruser
#      CLICKHOUSE_PASSWORD: datvirpass
#      CLICKHOUSE_DB: datvirdb
#    ports:
#      - "8123:8123"
#      - "9123:9000"
#    volumes:
#      - clickhouse_data:/var/lib/clickhouse
#      - ./clickhouse:/docker-entrypoint-initdb.d
#    networks:
#      - dbnet

  mongo:
    image: mongo:6.0.14
    environment:
      MONGO_INITDB_ROOT_USERNAME: datviruser
      MONGO_INITDB_ROOT_PASSWORD: datvirpass
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo:/docker-entrypoint-initdb.d
    networks:
      - dbnet

volumes:
  postgres_data:
  timescale_data:
  clickhouse_data:
  mongo_data:

networks:
  dbnet:
    name: datvirdbnet
