name: datvir

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: datviruser
      POSTGRES_PASSWORD: datvirpass
      POSTGRES_DB: datvirdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations/postgres:/docker-entrypoint-initdb.d
    networks:
      - datvirnet

  timescaledb:
    image: timescale/timescaledb-ha:pg16
    environment:
      POSTGRES_USER: datviruser
      POSTGRES_PASSWORD: datvirpass
      POSTGRES_DB: datvirdb
    ports:
      - "5433:5432"
    volumes:
      - tsdata:/var/lib/postgresql/data
      - ./migrations/timescale:/docker-entrypoint-initdb.d
    networks:
      - datvirnet

volumes:
  pgdata:
  tsdata:

networks:
  datvirnet:
